#!/usr/bin/env python

from aficio2060 import accounts

#import logging
#logging.basicConfig(level=logging.INFO)
#logging.getLogger('suds.client').setLevel(logging.DEBUG)


url = "file:///home/k3ks/Development/python-aficio2060/aficio2060.wsdl"
passString = "SCHEME=QkFTSUM=;UID:UserName=YWRtaW4=;PWD:Password=Puk/P3xsIqA8rqhvvupmYyImr3zjaH9j4WvufP9/qf7/Pv9mbHx/JCp+P3zgZr9nf6YkJ+hnvqc/JP6/Zz4+6v48rj98/2l8PyPopuFu/i4+/y8+aKbvr67+7r9/byZr/qj/4akmqD4iKT++5yl/Kn/iLqLq///p/6G+7OuqaOlraf4+;PES:Encoding=gwpwes003"

um = accounts.UserMaintSession(passString, url)

new_user = accounts.User(7777, "TEST123")
new_user.restrict = accounts.UserRestrict(True,True,True)
new_user.stats = accounts.UserStatistics()

um.add_user(new_user)

new_stats = accounts.UserStatistics()
new_user.stats = new_stats
um.set_user_info(new_user)

del um
